/*
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTaskDSLScopeProvider extends DelegatingScopeProvider {
}
