/*
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TaskDSLProposalProvider extends AbstractTaskDSLProposalProvider {
}
