/*
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.ide

import com.google.inject.Guice
import mars.ru.des.robot.TaskDSLRuntimeModule
import mars.ru.des.robot.TaskDSLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class TaskDSLIdeSetup extends TaskDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new TaskDSLRuntimeModule, new TaskDSLIdeModule))
	}
	
}
