/*
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.ui;

import com.google.inject.Injector;
import mars.ru.des.robot.tasks.ui.internal.TasksActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TaskDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(TasksActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		TasksActivator activator = TasksActivator.getInstance();
		return activator != null ? activator.getInjector(TasksActivator.MARS_RU_DES_ROBOT_TASKDSL) : null;
	}

}
