/**
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.generator;

import mars.ru.des.robot.generator.Brick1Generator;
import mars.ru.des.robot.taskDSL.Mission;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class TaskDSLGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IteratorExtensions.<EObject>head(resource.getAllContents());
    final Mission root = ((Mission) _head);
    if ((root != null)) {
      fsa.deleteFile("main.py");
      fsa.generateFile("brick1Main.py", Brick1Generator.generate(root));
    }
  }
}
