/**
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.taskDSL.impl;

import mars.ru.des.robot.taskDSL.Color;
import mars.ru.des.robot.taskDSL.DriveUntil;
import mars.ru.des.robot.taskDSL.Speed;
import mars.ru.des.robot.taskDSL.TaskDSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Drive Until</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mars.ru.des.robot.taskDSL.impl.DriveUntilImpl#getSpeed <em>Speed</em>}</li>
 *   <li>{@link mars.ru.des.robot.taskDSL.impl.DriveUntilImpl#getColor <em>Color</em>}</li>
 *   <li>{@link mars.ru.des.robot.taskDSL.impl.DriveUntilImpl#getObject <em>Object</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DriveUntilImpl extends ActionImpl implements DriveUntil
{
  /**
   * The default value of the '{@link #getSpeed() <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpeed()
   * @generated
   * @ordered
   */
  protected static final Speed SPEED_EDEFAULT = Speed.FAST;

  /**
   * The cached value of the '{@link #getSpeed() <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpeed()
   * @generated
   * @ordered
   */
  protected Speed speed = SPEED_EDEFAULT;

  /**
   * The default value of the '{@link #getColor() <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor()
   * @generated
   * @ordered
   */
  protected static final Color COLOR_EDEFAULT = Color.RED;

  /**
   * The cached value of the '{@link #getColor() <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor()
   * @generated
   * @ordered
   */
  protected Color color = COLOR_EDEFAULT;

  /**
   * The default value of the '{@link #getObject() <em>Object</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObject()
   * @generated
   * @ordered
   */
  protected static final mars.ru.des.robot.taskDSL.Object OBJECT_EDEFAULT = mars.ru.des.robot.taskDSL.Object.ROCK;

  /**
   * The cached value of the '{@link #getObject() <em>Object</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObject()
   * @generated
   * @ordered
   */
  protected mars.ru.des.robot.taskDSL.Object object = OBJECT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DriveUntilImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TaskDSLPackage.Literals.DRIVE_UNTIL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Speed getSpeed()
  {
    return speed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSpeed(Speed newSpeed)
  {
    Speed oldSpeed = speed;
    speed = newSpeed == null ? SPEED_EDEFAULT : newSpeed;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TaskDSLPackage.DRIVE_UNTIL__SPEED, oldSpeed, speed));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Color getColor()
  {
    return color;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setColor(Color newColor)
  {
    Color oldColor = color;
    color = newColor == null ? COLOR_EDEFAULT : newColor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TaskDSLPackage.DRIVE_UNTIL__COLOR, oldColor, color));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public mars.ru.des.robot.taskDSL.Object getObject()
  {
    return object;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setObject(mars.ru.des.robot.taskDSL.Object newObject)
  {
    mars.ru.des.robot.taskDSL.Object oldObject = object;
    object = newObject == null ? OBJECT_EDEFAULT : newObject;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TaskDSLPackage.DRIVE_UNTIL__OBJECT, oldObject, object));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TaskDSLPackage.DRIVE_UNTIL__SPEED:
        return getSpeed();
      case TaskDSLPackage.DRIVE_UNTIL__COLOR:
        return getColor();
      case TaskDSLPackage.DRIVE_UNTIL__OBJECT:
        return getObject();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TaskDSLPackage.DRIVE_UNTIL__SPEED:
        setSpeed((Speed)newValue);
        return;
      case TaskDSLPackage.DRIVE_UNTIL__COLOR:
        setColor((Color)newValue);
        return;
      case TaskDSLPackage.DRIVE_UNTIL__OBJECT:
        setObject((mars.ru.des.robot.taskDSL.Object)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TaskDSLPackage.DRIVE_UNTIL__SPEED:
        setSpeed(SPEED_EDEFAULT);
        return;
      case TaskDSLPackage.DRIVE_UNTIL__COLOR:
        setColor(COLOR_EDEFAULT);
        return;
      case TaskDSLPackage.DRIVE_UNTIL__OBJECT:
        setObject(OBJECT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TaskDSLPackage.DRIVE_UNTIL__SPEED:
        return speed != SPEED_EDEFAULT;
      case TaskDSLPackage.DRIVE_UNTIL__COLOR:
        return color != COLOR_EDEFAULT;
      case TaskDSLPackage.DRIVE_UNTIL__OBJECT:
        return object != OBJECT_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (speed: ");
    result.append(speed);
    result.append(", color: ");
    result.append(color);
    result.append(", object: ");
    result.append(object);
    result.append(')');
    return result.toString();
  }

} //DriveUntilImpl
