/*
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTaskDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(mars.ru.des.robot.taskDSL.TaskDSLPackage.eINSTANCE);
		return result;
	}
}
