/*
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TaskDSLRuntimeModule extends AbstractTaskDSLRuntimeModule {
}
