/**
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.ui;

import mars.ru.des.robot.ui.AbstractTaskDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TaskDSLUiModule extends AbstractTaskDSLUiModule {
  public TaskDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
