/**
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot;

import mars.ru.des.robot.AbstractTaskDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TaskDSLRuntimeModule extends AbstractTaskDSLRuntimeModule {
}
