/**
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.scoping;

import mars.ru.des.robot.scoping.AbstractTaskDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class TaskDSLScopeProvider extends AbstractTaskDSLScopeProvider {
}
