/**
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.taskDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Detectors</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mars.ru.des.robot.taskDSL.Detectors#getAvoids <em>Avoids</em>}</li>
 * </ul>
 *
 * @see mars.ru.des.robot.taskDSL.TaskDSLPackage#getDetectors()
 * @model
 * @generated
 */
public interface Detectors extends EObject
{
  /**
   * Returns the value of the '<em><b>Avoids</b></em>' containment reference list.
   * The list contents are of type {@link mars.ru.des.robot.taskDSL.Avoid}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Avoids</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Avoids</em>' containment reference list.
   * @see mars.ru.des.robot.taskDSL.TaskDSLPackage#getDetectors_Avoids()
   * @model containment="true"
   * @generated
   */
  EList<Avoid> getAvoids();

} // Detectors
