/**
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.taskDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Drive Until</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mars.ru.des.robot.taskDSL.DriveUntil#getSpeed <em>Speed</em>}</li>
 *   <li>{@link mars.ru.des.robot.taskDSL.DriveUntil#getColor <em>Color</em>}</li>
 *   <li>{@link mars.ru.des.robot.taskDSL.DriveUntil#getObject <em>Object</em>}</li>
 * </ul>
 *
 * @see mars.ru.des.robot.taskDSL.TaskDSLPackage#getDriveUntil()
 * @model
 * @generated
 */
public interface DriveUntil extends Action
{
  /**
   * Returns the value of the '<em><b>Speed</b></em>' attribute.
   * The literals are from the enumeration {@link mars.ru.des.robot.taskDSL.Speed}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Speed</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Speed</em>' attribute.
   * @see mars.ru.des.robot.taskDSL.Speed
   * @see #setSpeed(Speed)
   * @see mars.ru.des.robot.taskDSL.TaskDSLPackage#getDriveUntil_Speed()
   * @model
   * @generated
   */
  Speed getSpeed();

  /**
   * Sets the value of the '{@link mars.ru.des.robot.taskDSL.DriveUntil#getSpeed <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Speed</em>' attribute.
   * @see mars.ru.des.robot.taskDSL.Speed
   * @see #getSpeed()
   * @generated
   */
  void setSpeed(Speed value);

  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * The literals are from the enumeration {@link mars.ru.des.robot.taskDSL.Color}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Color</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see mars.ru.des.robot.taskDSL.Color
   * @see #setColor(Color)
   * @see mars.ru.des.robot.taskDSL.TaskDSLPackage#getDriveUntil_Color()
   * @model
   * @generated
   */
  Color getColor();

  /**
   * Sets the value of the '{@link mars.ru.des.robot.taskDSL.DriveUntil#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see mars.ru.des.robot.taskDSL.Color
   * @see #getColor()
   * @generated
   */
  void setColor(Color value);

  /**
   * Returns the value of the '<em><b>Object</b></em>' attribute.
   * The literals are from the enumeration {@link mars.ru.des.robot.taskDSL.Object}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Object</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object</em>' attribute.
   * @see mars.ru.des.robot.taskDSL.Object
   * @see #setObject(mars.ru.des.robot.taskDSL.Object)
   * @see mars.ru.des.robot.taskDSL.TaskDSLPackage#getDriveUntil_Object()
   * @model
   * @generated
   */
  mars.ru.des.robot.taskDSL.Object getObject();

  /**
   * Sets the value of the '{@link mars.ru.des.robot.taskDSL.DriveUntil#getObject <em>Object</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object</em>' attribute.
   * @see mars.ru.des.robot.taskDSL.Object
   * @see #getObject()
   * @generated
   */
  void setObject(mars.ru.des.robot.taskDSL.Object value);

} // DriveUntil
