/**
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.taskDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DSL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mars.ru.des.robot.taskDSL.DSL#getMissions <em>Missions</em>}</li>
 *   <li>{@link mars.ru.des.robot.taskDSL.DSL#getTasks <em>Tasks</em>}</li>
 * </ul>
 *
 * @see mars.ru.des.robot.taskDSL.TaskDSLPackage#getDSL()
 * @model
 * @generated
 */
public interface DSL extends EObject
{
  /**
   * Returns the value of the '<em><b>Missions</b></em>' containment reference list.
   * The list contents are of type {@link mars.ru.des.robot.taskDSL.Mission}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Missions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Missions</em>' containment reference list.
   * @see mars.ru.des.robot.taskDSL.TaskDSLPackage#getDSL_Missions()
   * @model containment="true"
   * @generated
   */
  EList<Mission> getMissions();

  /**
   * Returns the value of the '<em><b>Tasks</b></em>' containment reference list.
   * The list contents are of type {@link mars.ru.des.robot.taskDSL.Task}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tasks</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasks</em>' containment reference list.
   * @see mars.ru.des.robot.taskDSL.TaskDSLPackage#getDSL_Tasks()
   * @model containment="true"
   * @generated
   */
  EList<Task> getTasks();

} // DSL
