/**
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.taskDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Investigate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mars.ru.des.robot.taskDSL.Investigate#getSpeed <em>Speed</em>}</li>
 * </ul>
 *
 * @see mars.ru.des.robot.taskDSL.TaskDSLPackage#getInvestigate()
 * @model
 * @generated
 */
public interface Investigate extends Action
{
  /**
   * Returns the value of the '<em><b>Speed</b></em>' attribute.
   * The literals are from the enumeration {@link mars.ru.des.robot.taskDSL.Speed}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Speed</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Speed</em>' attribute.
   * @see mars.ru.des.robot.taskDSL.Speed
   * @see #setSpeed(Speed)
   * @see mars.ru.des.robot.taskDSL.TaskDSLPackage#getInvestigate_Speed()
   * @model
   * @generated
   */
  Speed getSpeed();

  /**
   * Sets the value of the '{@link mars.ru.des.robot.taskDSL.Investigate#getSpeed <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Speed</em>' attribute.
   * @see mars.ru.des.robot.taskDSL.Speed
   * @see #getSpeed()
   * @generated
   */
  void setSpeed(Speed value);

} // Investigate
