/**
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.taskDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Speak</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mars.ru.des.robot.taskDSL.Speak#getText <em>Text</em>}</li>
 * </ul>
 *
 * @see mars.ru.des.robot.taskDSL.TaskDSLPackage#getSpeak()
 * @model
 * @generated
 */
public interface Speak extends Action
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Text</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see mars.ru.des.robot.taskDSL.TaskDSLPackage#getSpeak_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link mars.ru.des.robot.taskDSL.Speak#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

} // Speak
