/**
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.taskDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see mars.ru.des.robot.taskDSL.TaskDSLPackage
 * @generated
 */
public interface TaskDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TaskDSLFactory eINSTANCE = mars.ru.des.robot.taskDSL.impl.TaskDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Mission</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mission</em>'.
   * @generated
   */
  Mission createMission();

  /**
   * Returns a new object of class '<em>Task</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task</em>'.
   * @generated
   */
  Task createTask();

  /**
   * Returns a new object of class '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action</em>'.
   * @generated
   */
  Action createAction();

  /**
   * Returns a new object of class '<em>Detector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Detector</em>'.
   * @generated
   */
  Detector createDetector();

  /**
   * Returns a new object of class '<em>Drive Until</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Drive Until</em>'.
   * @generated
   */
  DriveUntil createDriveUntil();

  /**
   * Returns a new object of class '<em>Investigate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Investigate</em>'.
   * @generated
   */
  Investigate createInvestigate();

  /**
   * Returns a new object of class '<em>Speak</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Speak</em>'.
   * @generated
   */
  Speak createSpeak();

  /**
   * Returns a new object of class '<em>Follow Line</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Follow Line</em>'.
   * @generated
   */
  FollowLine createFollowLine();

  /**
   * Returns a new object of class '<em>Avoid</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Avoid</em>'.
   * @generated
   */
  Avoid createAvoid();

  /**
   * Returns a new object of class '<em>Drive Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Drive Action</em>'.
   * @generated
   */
  DriveAction createDriveAction();

  /**
   * Returns a new object of class '<em>Move Back</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Move Back</em>'.
   * @generated
   */
  MoveBack createMoveBack();

  /**
   * Returns a new object of class '<em>Turn</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Turn</em>'.
   * @generated
   */
  Turn createTurn();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  TaskDSLPackage getTaskDSLPackage();

} //TaskDSLFactory
