/**
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.ide;

import mars.ru.des.robot.ide.AbstractTaskDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TaskDSLIdeModule extends AbstractTaskDSLIdeModule {
}
