/**
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import mars.ru.des.robot.TaskDSLRuntimeModule;
import mars.ru.des.robot.TaskDSLStandaloneSetup;
import mars.ru.des.robot.ide.TaskDSLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TaskDSLIdeSetup extends TaskDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    TaskDSLRuntimeModule _taskDSLRuntimeModule = new TaskDSLRuntimeModule();
    TaskDSLIdeModule _taskDSLIdeModule = new TaskDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_taskDSLRuntimeModule, _taskDSLIdeModule));
  }
}
