/*
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.ui.tests;

import com.google.inject.Injector;
import mars.ru.des.robot.tasks.ui.internal.TasksActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TaskDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TasksActivator.getInstance().getInjector("mars.ru.des.robot.TaskDSL");
	}

}
