/*
 * generated by Xtext 2.15.0
 */
package mars.ru.des.robot.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TaskDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("mars/ru/des/robot/parser/antlr/internal/InternalTaskDSL.tokens");
	}
}
